---

# Eureka client config
eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka"

# Admin client config
spring:
  boot:
    admin:
      client:
        url: "http://localhost:9090"

# Actuator
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: "always"
